r"""MISMIP+ OSSE reference: SSA spin-up → Hybrid bootstrap → 'truth' fields.

Synthetic-twin testbed for "how many vertical-velocity observations constrain
deformation (shear) over ridges". The reference is generated by spinning the ice
stream up cheaply with SSA, then re-solving with the HybridModel under the SAME
forcing (fluidity, friction, geometry) so the truth carries vertical shear over
the ridges. Synthetic observations are sampled from the Hybrid truth elsewhere.

Geometry: MISMIP+ bed (Asay-Davis et al. 2016) + controlled transverse ridges
(so "shear over ridges" is clean/interpretable). True fluidity is spatially
structured (the inversion target). Friction is a fixed perturbed field.

Writes mesh/mismip_truth.h5 (2D fields + Hybrid surface velocity + ε_zz) and
mesh/mismip_truth_3d.h5 (the extruded Hybrid state).
"""
import numpy as np
import firedrake
import icepack
import icepack.models.friction
from firedrake import (
    Constant, Function, FunctionSpace, VectorFunctionSpace,
    RectangleMesh, MeshHierarchy, ExtrudedMesh, CheckpointFile,
    SpatialCoordinate, interpolate, exp, sin, sqrt, inner, max_value, dx, assemble,
    conditional, as_vector,
)
from icepack.constants import (
    ice_density as ρ_I, water_density as ρ_W, gravity as g,
    weertman_sliding_law as m,
)
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent
Lx, Ly = 640e3, 80e3
A0 = Constant(20.0)        # fluidity scale (θ_A = log(A/A0))
VDEGREE = 4                # Hybrid vertical (GL) degree — rich shear profile
FSCALE = 1.0               # overall basal-friction multiplier (sticky bed → vertical shear)
STICKY = 0.0               # extra friction over ridge CRESTS (induces shear over ridges)
RIDGE_WL = 60e3            # ridge wavelength (shared by bed ridges + sticky friction)
SOLVER = {
    "snes_type": "newtonls", "snes_linesearch_type": "bt",
    "snes_max_it": 100, "snes_rtol": 1e-7,
    "ksp_type": "preonly", "pc_type": "lu", "pc_factor_mat_solver_type": "mumps",
}


def mismip_bed(Q):
    x, y = SpatialCoordinate(Q.mesh())
    X = x / Constant(300e3)
    B_x = -150 - 728.8 * X**2 + 343.91 * X**4 - 50.57 * X**6
    f_c, d_c, w_c = 4e3, 500, 24e3
    B_y = d_c * (1 / (1 + exp(-2 * (y - Ly / 2 - w_c) / f_c))
                 + 1 / (1 + exp(+2 * (y - Ly / 2 + w_c) / f_c)))
    return max_value(B_x + B_y, Constant(-720.0))


def transverse_ridges(Q, amp=120.0, wavelength=60e3):
    """Controlled bed ridges transverse to flow (x), amplitude `amp` (m)."""
    x, y = SpatialCoordinate(Q.mesh())
    taper = max_value(0.0, 1.0 - x / Constant(520e3))   # fade out toward the front
    return amp * taper * sin(2 * np.pi * x / Constant(wavelength))


def true_fluidity(Q):
    """Spatially structured TRUE log-fluidity θ_A (the inversion target)."""
    x, y = SpatialCoordinate(Q.mesh())
    # softer (warmer) ice downstream + a cross-flow band — gives recoverable structure
    return (Constant(0.6) * (x / Constant(Lx))
            + Constant(0.4) * sin(2 * np.pi * x / Constant(160e3))
            * exp(-((y - Ly / 2) / Constant(20e3))**2))


def true_friction(Q):
    x, y = SpatialCoordinate(Q.mesh())
    C = Constant(0.0)
    rng = np.random.default_rng(7)
    for _ in range(25):
        xi, yi, ai = rng.random() * Lx, rng.random() * Ly, rng.random() * 1e-2
        C = C + ai * exp(-((x - Constant(xi))**2 + (y - Constant(yi))**2) / Constant(5500.0)**2)
    base = C + Constant(5e-3) - x**(1.0 / 3) * Constant(5e-3) / Constant(Lx)**(1.0 / 3)
    # sticky ridges: friction enhanced over the bed-ridge crests (sin>0) so ice grinds
    # slowly there → vertical shear concentrated OVER RIDGES (the OSSE target signal).
    taper = max_value(0.0, 1.0 - x / Constant(520e3))
    crest = max_value(0.0, sin(2 * np.pi * x / Constant(RIDGE_WL)))
    return Constant(FSCALE) * base * (1.0 + Constant(STICKY) * taper * crest)


def friction_weertman(**kw):
    u, h, s, C = kw["velocity"], kw["thickness"], kw["surface"], kw["friction"]
    ϕ = 1 - ρ_W * g * max_value(0, h - s) / (ρ_I * g * h)
    return icepack.models.friction.bed_friction(velocity=u, friction=C * ϕ)


def spd(uu):
    return float(np.sqrt((uu.dat.data_ro ** 2).sum(axis=1)).max())


def main():
    import argparse
    global FSCALE, STICKY
    ap = argparse.ArgumentParser()
    ap.add_argument("--T_spin", type=float, default=3000.0)   # SSA vol is steady by ~1600 yr; 3000 gives margin
    ap.add_argument("--fscale", type=float, default=FSCALE, help="overall friction multiplier")
    ap.add_argument("--sticky", type=float, default=STICKY, help="extra friction over ridge crests")
    args = ap.parse_args()
    FSCALE, STICKY = args.fscale, args.sticky
    print(f"=== MISMIP+ OSSE reference (SSA spin-up {args.T_spin:.0f}yr → Hybrid bootstrap) ===", flush=True)
    print(f"    friction: FSCALE={FSCALE}, STICKY={STICKY} (sticky ridges → vertical shear)", flush=True)
    ny = 25
    nx = int(Lx / Ly) * ny
    mesh2d = MeshHierarchy(RectangleMesh(nx, ny, Lx, Ly), 2)[1]
    Q = FunctionSpace(mesh2d, "CG", 1)
    V = VectorFunctionSpace(mesh2d, "CG", 1)
    print(f"Mesh2d: {mesh2d.num_vertices()} verts ({nx*2}x{ny*2})", flush=True)

    bed = interpolate(mismip_bed(Q) + transverse_ridges(Q), Q)
    θA_true = interpolate(true_fluidity(Q), Q)
    C_true = interpolate(true_friction(Q), Q)
    A = interpolate(A0 * exp(θA_true), Q)
    smb = interpolate(Constant(0.3), Q)
    print(f"  bed=[{bed.dat.data.min():.0f},{bed.dat.data.max():.0f}] m; "
          f"θA_true=[{θA_true.dat.data.min():.2f},{θA_true.dat.data.max():.2f}]", flush=True)

    # ── SSA spin-up to (near) steady state ──
    model = icepack.models.IceStream(friction=friction_weertman)
    solver = icepack.solvers.FlowSolver(model, dirichlet_ids=[1], ice_front_ids=[2], side_wall_ids=[3, 4],
                                        diagnostic_solver_type="petsc", diagnostic_solver_parameters=SOLVER)
    h = interpolate(Constant(100.0), Q)
    s = icepack.compute_surface(thickness=h, bed=bed)
    x, _ = SpatialCoordinate(mesh2d)
    u = interpolate(as_vector([90 * x / Lx + 10, Constant(0.0)]), V)
    u = solver.diagnostic_solve(velocity=u, thickness=h, surface=s, fluidity=A, friction=C_true)
    print(f"  SSA primed: speed max {spd(u):.0f} m/yr", flush=True)

    dt, T_spin = 2.0, args.T_spin
    nstep = int(T_spin / dt)
    for step in range(nstep):
        h = solver.prognostic_solve(dt, thickness=h, velocity=u, accumulation=smb,
                                    thickness_inflow=interpolate(Constant(100.0), Q))
        h = interpolate(max_value(h, Constant(1.0)), Q)
        s = icepack.compute_surface(thickness=h, bed=bed)
        u = solver.diagnostic_solve(velocity=u, thickness=h, surface=s, fluidity=A, friction=C_true)
        if step % max(1, nstep // 10) == 0:
            vol = assemble(h * dx) / 1e9
            print(f"  SSA spin t={step*dt:6.0f}: vol={vol:.2f} km³, "
                  f"hmax={h.dat.data.max():.0f}", flush=True)

    # ── Hybrid bootstrap: same forcing, vertically resolved ──
    # GLL vertical family (nodes at ζ=0,1) + vertical velocity w as the observable —
    # matches the working proposal notebook (mismip_vertical.ipynb). GL (no endpoint
    # nodes) was the bug: it mangled the surface/basal structure ApRES depends on.
    print("Bootstrapping to HybridModel (same forcing)...", flush=True)
    mesh3d = ExtrudedMesh(mesh2d, layers=1)
    QR = FunctionSpace(mesh3d, "CG", 1, vfamily="R", vdegree=0)
    VR = VectorFunctionSpace(mesh3d, "CG", 1, vfamily="R", vdegree=0, dim=2)
    VV = VectorFunctionSpace(mesh3d, "CG", 1, vfamily="GLL", vdegree=VDEGREE, dim=2)
    h3 = icepack.utilities.lift3d(h, QR)
    s3 = icepack.utilities.lift3d(s, QR)
    A3 = icepack.utilities.lift3d(A, QR)
    C3 = icepack.utilities.lift3d(C_true, QR)
    u3 = Function(VV).interpolate(icepack.utilities.lift3d(u, VR))

    hyb = icepack.models.HybridModel(friction=friction_weertman)
    hsolver = icepack.solvers.FlowSolver(hyb, dirichlet_ids=[1], ice_front_ids=[2], side_wall_ids=[3, 4],
                                         diagnostic_solver_type="petsc", diagnostic_solver_parameters=SOLVER)
    u3 = hsolver.diagnostic_solve(velocity=u3, thickness=h3, surface=s3, fluidity=A3, friction=C3)
    print(f"  Hybrid solved: surface speed max {spd(icepack.depth_average(u3)):.0f} m/yr", flush=True)

    # vertical velocity w (the ApRES observable) — the higher-order signal SSA lacks
    Qw = FunctionSpace(mesh3d, "CG", 1, vfamily="GLL", vdegree=VDEGREE)
    w = icepack.utilities.vertical_velocity(velocity=u3, thickness=h3, basal_mass_balance=Constant(0.0))
    w3 = Function(Qw, name="w_3d").project(w)
    print(f"  vertical velocity w range: [{w3.dat.data_ro.min():.4e}, {w3.dat.data_ro.max():.4e}] m/yr", flush=True)

    # ε_zz = -(∂u_x/∂x+∂u_y/∂y), depth-resolved, as an alternate observable
    eps = icepack.models.hybrid.horizontal_strain_rate(velocity=u3, thickness=h3, surface=s3)
    eps_zz3 = Function(Qw, name="eps_zz_3d").interpolate(-(eps[0, 0] + eps[1, 1]))

    # 2D fields (on mesh2d) for masking + the SSA inversion; u_surface = SSA plug velocity
    # (a clean depth-constant warm-start — true surface velocity is sampled from u3 at ζ≈1)
    with CheckpointFile(str(DATA / "mesh" / "mismip_truth.h5"), "w") as chk:
        chk.save_mesh(mesh2d)
        chk.save_function(Function(Q, name="thickness").assign(h), name="thickness")
        chk.save_function(Function(Q, name="surface").assign(s), name="surface")
        chk.save_function(Function(Q, name="bed").assign(bed), name="bed")
        chk.save_function(Function(Q, name="log_fluidity_true").assign(θA_true), name="log_fluidity_true")
        chk.save_function(Function(Q, name="friction_true").assign(C_true), name="friction_true")
        chk.save_function(Function(V, name="u_surface").assign(u), name="u_surface")
    with CheckpointFile(str(DATA / "mesh" / "mismip_truth_3d.h5"), "w") as chk:
        chk.save_mesh(mesh3d)
        chk.save_function(u3, name="velocity_3d")
        chk.save_function(w3, name="w_3d")                     # vertical velocity — primary observable
        chk.save_function(eps_zz3, name="eps_zz_3d")          # depth-resolved alternate
        chk.save_function(Function(QR, name="thickness_3d").interpolate(h3), name="thickness_3d")
        chk.save_function(Function(QR, name="surface_3d").interpolate(s3), name="surface_3d")
        chk.save_function(Function(QR, name="friction_3d").interpolate(C3), name="friction_3d")  # for inversion (no cross-mesh)
    print("Saved mesh/mismip_truth.h5 (+ _3d). Done!", flush=True)


if __name__ == "__main__":
    main()
